### ISSUE TITLE
Support CircleCI Enterprise setups

### ISSUE THREAD

**Issue by acburdine** [nrwl/nx-orb#23]
## Describe Request:

I'm looking at using this orb in a self-hosted CircleCI instance, which has a different instance URL. However, it looks like this orb has the public CircleCI Cloud API url hardcoded, meaning this orb is currently not usable for me 😕 .

However, after looking through the codebase, I believe this can be solved with some simple changes (I'm willing to contribute said changes - just wanted to open an issue first to make sure there aren't any additional things I need to consider 😄).

A couple different approaches I think would work:
- Allow specifying the CircleCI base url via an environment variable, e.g. `CIRCLE_BASE_URL`, or
- Modifying the regular expression [here](https://github.com/nrwl/nx-orb/blob/main/src/scripts/find-successful-workflow.js#L53) to extract the CircleCI instance URL as well as the project url.

I think the second approach makes more sense from a UX perspective, as it requires no changes for users of this orb; however, there could be edge cases with that approach that I'm not seeing.

## Examples:

Ideally, this would require no changes from a user perspective beyond (potentially) specifying the CircleCI instance URL as an environment variable.

## Supporting Documentation Links:

- [CircleCI Server v3 Overview](https://circleci.com/docs/2.0/server-3-overview/)

**Comment by meeroslav** [comment]
Hi @acburdine,

Thank you for opening this issue. Please feel free to implement a proposal (PR). You can test it out on your solution using `nrwl/nx@dev:alpha` (which holds the last dev-built version).

Looking forward to your contribution! 🚀
