### ISSUE TITLE
Find last successful workflow for tag

### ISSUE THREAD

**Issue by denat** [nrwl/nx-orb#28]
## Describe Request:

My team uses tags for releases, which currently doesn't work nicely with `nx-orb/set-shas` as the script always requires a branch name to find the last successful workflow, so it'll never be able to find a previously successful _tagged_ workflow.

As a proposed solution, we would like to omit the branch name entirely and search exclusively by workflow name to find the base SHA.

Usage example:

```yml
    steps:
      - checkout
      - nx/set-shas:
          workflow-name: foo-service-production
          ignore-branch-name: true
```

This flag would essentially allow us to remove the branch name from the CircleCI API call, something like:

```js
async function findSuccessfulCommit(branch, workflowName) {
  const url = `https://${host}/api/v2/project/${project}/pipeline${ignoreBranchName ? '' : `?branch=${branch}`}`;
  // ...
```

If this seems like a sensible way to go, I'd love to make a PR.

### Partial output of our "Preparing Environment Variables" step

```
Using build environment variables:
  BASH_ENV=/tmp/.bash_env-628e3db1e9fb6411ff4e35e8-0-build
  CI=true
  CIRCLECI=true
  CIRCLE_BRANCH=
  CIRCLE_BUILD_NUM=3259
  CIRCLE_BUILD_URL=<REDACTED>
  CIRCLE_COMPARE_URL=
  CIRCLE_JOB=run-tests-production
  CIRCLE_NODE_INDEX=0
  CIRCLE_NODE_TOTAL=1
  CIRCLE_PREVIOUS_BUILD_NUM=3258
  CIRCLE_PROJECT_REPONAME=<REDACTED>
  CIRCLE_PROJECT_USERNAME=<REDACTED>
  CIRCLE_REPOSITORY_URL=<REDACTED>
  CIRCLE_SHA1=c3e017d5f1a96da934c502975ae047adb5b86b5e
  CIRCLE_SHELL_ENV=/tmp/.bash_env-628e3db1e9fb6411ff4e35e8-0-build
  CIRCLE_STAGE=run-tests-production
  CIRCLE_TAG=v0.0.29
  CIRCLE_USERNAME=denat
  CIRCLE_WORKFLOW_ID=c8d8aa24-dcff-4251-9867-7a0b77a93a71
  CIRCLE_WORKFLOW_JOB_ID=3f70c93c-7e3a-4e73-8dfa-21a2d8ca428c
  CIRCLE_WORKFLOW_UPSTREAM_JOB_IDS=
  CIRCLE_WORKFLOW_WORKSPACE_ID=c8d8aa24-dcff-4251-9867-7a0b77a93a71
  CIRCLE_WORKING_DIRECTORY=~/project
```

**Comment by fkontic** [comment]
I had the same problem as you did so I forked the orb and made it work with tags. You can see the change [here](https://github.com/fkontic/nx-orb/commit/3ded946bf5c9085913ecd22abd297aa3856b539c) and you can use it like this `nx: fkontic/nx@0.2.0`.

@meeroslav If you like the changes, I can make a PR. If not, I'll just use my forked version.

**Comment by meeroslav** [comment]
Thank you @fkontic, I will look more closely next week.
