### ISSUE TITLE
nx@1.1.0 release to circleci orb repo

### ISSUE THREAD

**Issue by michael-golden** [nrwl/nx-orb#4]
## Orb version:
1.1.0

## What happened:
  nx: nrwl/nx@1.1.0 is not available in the circleci orb repository.

## Expected behavior:

Can you publish the latest release to the circleci orb repository?
The current available version is 1.0.0.  version 1.1.0 includes the CIRCLE_API_TOKEN change that is necessary to derive the correct SHAs from the circleci API.

**Comment by meeroslav** [comment]
Hi @michael-golden, thank you for reaching out.

We are trying to resolve it. Hopefully, it will be solved very soon.

Check the thread on the original PR here: https://github.com/nrwl/nx-orb/pull/3

**Comment by meeroslav** [comment]
We have released the version 1.1.0 today. Please let us know if there are any issues.
