### ISSUE TITLE
Pipeline times out when looking for workflow on branches with plenty of pipelines

### ISSUE THREAD

**Issue by pedroyan** [nrwl/nx-orb#42]
## Orb version:
1.6.0

## What happened:
Pipeline times out when Nx tries to resolve the `BASE_SHA` by Workflow Name from a long-running branches with lots of pipelines executions

![image](https://user-images.githubusercontent.com/11574849/190544111-1f4357e9-1db0-4364-ad06-7eb2dd5dd1d7.png)

## Expected behavior:

Pipeline is able to resolve `BASE_SHA`  on long-running branches

### Steps to reproduce
1. Create a repository
2. Create a Circle CI `config.yml` file
3. Trigger a lot of pipeline executions for a single branch
4. Configure `set-shas` to look for a `workflow-name` that does not exist so it runs through all pipelines
      - The problem also applies if the successful workflow was completed in a pipeline that's behind many executions

**Comment by pedroyan** [comment]
I forked the repository and when I get some time, I'm thinking about fixing the problem by executing many `isWorkflowSuccessful` concurrently and then picking the latests successful one from the pipelines queried on that batch.

![image](https://user-images.githubusercontent.com/11574849/190545002-b2a3897e-a73d-4674-9e0a-41fde32767d6.png)

Does that approach make sense?

**Comment by eladhaim** [comment]
related to #43, i've created a pr to fix this issue. waiting for maintainers approval.

**Comment by meeroslav** [comment]
This should be fixed with #44.

If you still encounter it, please let me know to reopen this issue.
