### ISSUE TITLE
Methodology for determining last successful pipeline run doesn't work if there are multiple kinds of pipelines

### ISSUE THREAD

**Issue by ajwootto** [nrwl/nx-orb#7]
## What happened:

We have a setup for our CD system where we run a particular pipeline when new code is merged to main. That pipeline uses the `nx affected` commands for building and testing. 

When that pipeline is finished, our code is deployed. The deployment event triggers a second pipeline to run which executes e2e tests. That pipeline does not include any Nx commands. 

The orb currently interprets a successful completion of either one of these pipelines as the "last successful" run on the main branch. However, only the first "build & test" pipeline is the one that should be considered as a "run". This causes commands that use `nx affected` to receive the wrong sha.

## Expected behavior:

Ideally, the orb would handle for this case by filtering the set of pipelines its getting from the CircleCI API using the name of the pipeline that it's currently running in (if that's possible). Or provide a parameter that can specify the name of the pipeline to watch for.

**Comment by meeroslav** [comment]
Thank you @ajwootto for creating the issue.

Your proposal is correct, having an optional second parameter to specify with workflow to use would solve your issue.
This is a similar PR for GitHub action we just merged in today - https://github.com/nrwl/nx-set-shas/pull/7.

If you want you can propose a PR for this.

**Comment by meeroslav** [comment]
Fixed by #9
